### ISSUE TITLE
Implement Site component

### ISSUE THREAD

**Issue by MUCHZER** [tabler/tabler-vue#14]
Existing code https://github.com/tabler/tabler-vue/tree/master/src/components/Site

**Comment by isneezy** [comment]
@Nilpo @MUCHZER I can start with this one! As i said we need to discuss more about the implementation

**Comment by isneezy** [comment]
- The [SiteWrapper](https://github.com/tabler/tabler-vue/blob/master/src/components/Site/SiteWrapper.vue) component, Should we continue to Call it `SiteWrapper` or Just `Site`? (this is only for convention)
- What would be the best way to handle click on the Hamburger in mobile?
